name: Release Electron App

permissions:
  contents: write
  
on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/**' 
  workflow_dispatch:

jobs:
  package:
    runs-on: windows-latest  # Changed to Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Read Package Name and Version
        id: get_package_info
        run: |
          $PACKAGE_NAME = node -p "require('./package.json').name"
          $VERSION = node -p "require('./package.json').version"
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $env:GITHUB_ENV
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV

      - name: Package Electron App
        run: npm run package

      - name: Publish Electron App
        run: npm run publish

      - name: Zip Package
        run: |
          # Using PowerShell to create the zip file
          $zipFilePath = "${{ github.workspace }}\$($env:PACKAGE_NAME)-$($env:VERSION).zip"
          $sourceFolder = "out\$($env:PACKAGE_NAME)-win32-x64"
          Compress-Archive -Path $sourceFolder\* -DestinationPath $zipFilePath

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "v${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload release asset (Zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}\${{ env.PACKAGE_NAME }}-${{ env.VERSION }}.zip  # Corrected
          asset_name: ${{ env.PACKAGE_NAME }}-${{ env.VERSION }}.zip  # Corrected
          asset_content_type: application/zip

      - name: Upload release asset (Setup.exe)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out\make\squirrel.windows\x64\${{ env.PACKAGE_NAME }}-${{ env.VERSION }} Setup.exe  # Corrected
          asset_name: ${{ env.PACKAGE_NAME }}-${{ env.VERSION }}.exe  # Corrected
          asset_content_type: application/octet-stream

